### ISSUE TITLE
Assertion `seqPos == read->core.l_qseq' failed

### ISSUE THREAD

**Issue by holmrenser** [sc932/ALE#11]
I have integrated ALE in a pipeline I run on a large number of samples.
For some reason I get the error:
_ALE: ALElike.c:618: getContributionsForPositions: Assertion `seqPos == read->core.l_qseq' failed._
But only for a few assemblies of a few samples. As I am not a C programmer I don't really understand what is going wrong here...

**Comment by robegan21** [comment]
closing
