### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by sjackman** [sc932/ALE#14]
There have been a number of commits to master since the last tagged release of `20130717`. Could you please tag a new release?

**Comment by robegan21** [comment]
done.  Thanks!

**Comment by sjackman** [comment]
Thanks, Rob!

**Comment by sjackman** [comment]
The SHA-256 for this tarball is… `1234578…`! So close!

**Comment by sjackman** [comment]
I've opened PR https://github.com/brewsci/homebrew-bio/pull/418 to update the formula in Brewsci/bio for Homebrew and Linuxbrew.
