### ISSUE TITLE
Error! Assembly fasta does not match alignment file

### ISSUE THREAD

**Issue by SabSN** [sc932/ALE#17]
Hi
I am trying to run ALE to asses my assembly file (from Unicycler). I used BWA to create a sam file of the alignment, whit this command: 
bwa mem -t4 ref.fna assembly.fasta > ale-pre.sam
- the reference was indexed before hand by bwa
Then I sorted and indexed 
samtools sort > ale.aln.sam
samtools index ale.aln.sam

Now I am getting an error: Assembly fasta does not match alignment file

**Comment by robegan21** [comment]
Hi,
Sorry for the late response.  

The error indicates that the sequences within the assembly.fasta does not have the same names, lengths, ordering as is encoded within the sam/bam file -- this is a typical error where \ users may align reads to one assembly file but attempt to analyze using a different one... so something went wrong in your alignment or conversion into a sam/bam file.  

Additionally ALE has never been tested using a SAM file, so I suggest you create a sorted BAM file.  Please look to the samtools manual for the proper way to convert a SAM file to a sorted BAM file.

**Comment by SabSN** [comment]
The reference did not match my assembly.
